project:
  type: website
  render:
    - "*.qmd"
format-links: true
prefer-html: true
license: "CC by"
copyright:
  holder: Gaelen Guzman
  year: 2025
website:
  title: "GaelenGuzman.github.io"
  repo-url: https://github.com/gaelenDG/GaelenGuzman.github.io
  repo-actions: [source, issue]
  # favicon: assets/images/icon.svg
  navbar:
    pinned: true
    # logo: assets/images/logo.png
    right:
      - text: "About" 
        href: about.html
      - text: "Contact"
        href: contact.html
    left: 
      - text: "Hobby EE Projects"
        menu:
          - text: "Mushroom Lamp"
            href: HobbyEEProjects/MushroomLamp_v1.html
          - text: "Light-up Baby Book"
            href: HobbyEEProjects/LightUpBabyBook.html
          - text: "Mushroom Lamp v2"
            href: HobbyEEProjects/MushroomLamp_v2.html
          - text: "Magnetic Stirbar Lamp"
            href: HobbyEEProjects/MagneticStirbarLamp.html
  sidebar: true 
  page-navigation: true
  # footer:
  #   left:
  #     - text: "© 2025 Gaelen Guzman"
  #   right:
  #     - text: "Built with Quarto"
  #     - text: "Source"
  #       href: https://github.com/gaelenDG/GaelenGuzman.github.io

format:
  html:
    lightbox:
      match: auto
      effect: fade
      desc-position: bottom
      loop: true
    mainfont: Charter
    theme: [Flatly, assets/css/theme_customizations.scss]
    css: assets/css/styles.css
    toc: true
    sidebar: true
